name: draw
description: Flutter Application to draw on screen.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  image:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_colorpicker: any

flutter:
  assets:
    - assets/

  uses-material-design: true
